"""Build the word-character table of judge-protocol-checkers-v1 from the Unicode Character Database.

`contains` with `wholeWords` treats `_` and every code point of General_Category L* or N* as a word
character. Reading those categories from the runtime (Python's unicodedata, or a JavaScript
engine's \\p{L} and \\p{N}) makes the answer depend on which Unicode version that runtime ships, so
the table is pinned instead: Unicode 17.0.0, from the file below, checked by its SHA-256.

The same ranges appear in three places, and tests hold them identical:
- SPEC.md of the profile (the authority, pinned with the profile);
- judge-service/src/checkers/word-characters.js (the live judge);
- web/word-characters.js (the in-browser verifier).

Usage (from this directory): python3 word_ranges.py <DerivedGeneralCategory.txt> [--write]
Without --write it only checks that all three copies match the file.
"""
import hashlib
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE_URL = "https://www.unicode.org/Public/17.0.0/ucd/extracted/DerivedGeneralCategory.txt"
SOURCE_SHA256 = "d62e5bab70ca74f099343f71224fa051cb1fdd61a1ab45c0488c44cfc0b6102e"
WORD_CATEGORIES = {"Lu", "Ll", "Lt", "Lm", "Lo", "Nd", "Nl", "No"}
SPEC = HERE / "profiles/judge-protocol-rvr-v0/SPEC.md"
JS_TARGETS = (HERE.parent / "judge-service/src/checkers/word-characters.js", HERE.parent / "web/word-characters.js")
FENCE = "```judge-protocol-word-ranges\n"


def ranges_from(ucd: bytes) -> list[tuple[int, int]]:
    if hashlib.sha256(ucd).hexdigest() != SOURCE_SHA256:
        raise SystemExit(f"not the pinned Unicode 17.0.0 file (sha256 differs); download {SOURCE_URL}")
    points: list[tuple[int, int]] = []
    for line in ucd.decode("utf-8").splitlines():
        body = line.split("#", 1)[0].strip()
        if not body:
            continue
        span, category = (part.strip() for part in body.split(";"))
        if category not in WORD_CATEGORIES:
            continue
        first, _, last = span.partition("..")
        points.append((int(first, 16), int(last or first, 16)))
    merged: list[tuple[int, int]] = []
    for start, end in sorted(points):
        if merged and start <= merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], max(merged[-1][1], end))
        else:
            merged.append((start, end))
    return merged


def render(ranges: list[tuple[int, int]]) -> list[str]:
    return [f"{a:04X}" if a == b else f"{a:04X}-{b:04X}" for a, b in ranges]


def js_module(lines: list[str]) -> str:
    rows = [", ".join(json.dumps(item) for item in lines[i:i + 10]) for i in range(0, len(lines), 10)]
    return (
        "// Generated by rvr/word_ranges.py from the Unicode 17.0.0 Character Database; do not edit.\n"
        f"// Source: {SOURCE_URL}\n"
        f"// sha256 {SOURCE_SHA256}\n"
        "// Word characters for `contains` with wholeWords: these ranges (General_Category L* and N*)\n"
        "// plus U+005F. Pinned so the answer never depends on the runtime's own Unicode version.\n"
        "export const WORD_RANGES = [\n  " + ",\n  ".join(rows) + ",\n];\n"
    )


def spec_block(text: str) -> list[str]:
    start = text.index(FENCE) + len(FENCE)
    return text[start:text.index("```", start)].split()


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__)
        return 2
    lines = render(ranges_from(Path(sys.argv[1]).read_bytes()))
    if "--write" in sys.argv:
        spec = SPEC.read_text(encoding="utf-8")
        start = spec.index(FENCE) + len(FENCE)
        end = spec.index("```", start)
        SPEC.write_text(spec[:start] + "\n".join(lines) + "\n" + spec[end:], encoding="utf-8", newline="\n")
        for target in JS_TARGETS:
            target.write_text(js_module(lines), encoding="utf-8", newline="\n")
    problems = []
    if spec_block(SPEC.read_text(encoding="utf-8")) != lines:
        problems.append("SPEC.md")
    for target in JS_TARGETS:
        found = re.search(r"export const WORD_RANGES = \[(.*)\];", target.read_text(encoding="utf-8"), re.S)
        if not found or json.loads("[" + found.group(1).rstrip().rstrip(",") + "]") != lines:
            problems.append(str(target.relative_to(HERE.parent)))
    if problems:
        print("differs from Unicode 17.0.0:", ", ".join(problems))
        return 1
    print(f"{len(lines)} ranges, identical in SPEC.md and both JavaScript copies")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
